package cotabo

class BuggyController {

	def index = {
		//10000 bytes
		def message = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod urna eget tellus congue faucibus. Integer feugiat urna bibendum nulla accumsan condimentum consectetur risus rhoncus. In non quam velit, in eleifend justo. Sed luctus lectus eget nisi pulvinar aliquet sed in massa. Cras non ligula eu libero elementum auctor. Praesent posuere molestie ante sed condimentum. Maecenas consequat hendrerit lobortis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec fringilla, libero non faucibus lacinia, enim libero facilisis dolor, nec pretium quam mi sed magna. Proin porta tortor vel metus tincidunt porttitor. Aenean mollis tincidunt dui eu bibendum. Donec non elit vitae nisl dapibus tincidunt in vitae diam. Fusce at turpis at eros placerat vestibulum.

Mauris sit amet interdum diam. Quisque imperdiet cursus gravida. Cras cursus eros a arcu eleifend eleifend. Vestibulum condimentum metus et purus varius viverra eu ut nunc. Mauris scelerisque ligula et nisi rutrum sed egestas tortor ornare. Ut quis rutrum neque. Vestibulum diam ante, egestas vel condimentum quis, lobortis vel ante. Integer posuere, diam sit amet dictum aliquam, nisi mauris vestibulum dui, vel dapibus nunc arcu tempor felis. Suspendisse scelerisque, est a tempus feugiat, justo nibh volutpat est, sed vehicula leo metus in eros. Donec feugiat aliquam mollis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam egestas, turpis eget egestas semper, lacus urna aliquam enim, nec consequat metus urna in velit. In ut tortor tortor, in pellentesque nisl. Etiam faucibus risus at tellus mollis ultricies sagittis nisi aliquet. Quisque erat urna, gravida id tincidunt ut, suscipit in arcu. Maecenas adipiscing, est at congue gravida, ipsum diam fermentum sem, et vulputate enim est et justo.

Nam vehicula dictum nibh, id malesuada neque aliquam id. Donec pulvinar purus quis odio mattis fringilla. Aenean sit amet erat libero. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur semper eros a tellus euismod vestibulum. Curabitur laoreet egestas nulla, nec rutrum sem vulputate lacinia. Proin id mollis libero. Duis iaculis, odio sed blandit egestas, enim augue malesuada quam, in adipiscing dolor arcu quis purus. Sed pulvinar turpis vehicula risus adipiscing egestas. Nulla euismod tincidunt rutrum. Suspendisse sed risus sit amet enim commodo porta. In odio eros, mattis vel iaculis vel, faucibus vel ipsum.

Etiam nec metus non lorem luctus aliquet ac laoreet velit. Nulla facilisi. Nulla placerat ipsum id orci vehicula quis auctor arcu elementum. Morbi sodales tincidunt leo vitae molestie. Cras odio diam, scelerisque ac lobortis auctor, dignissim sed erat. Vestibulum eros mauris, ultricies non ornare at, tempus ut urna. Nulla ut justo nulla.

Sed accumsan, risus iaculis luctus iaculis, mauris risus sodales ligula, faucibus pulvinar neque tellus eu lorem. Duis mollis malesuada accumsan. Aenean sed leo ut nisi ullamcorper pellentesque. Fusce pulvinar luctus vulputate. Vestibulum auctor auctor ante ut rhoncus. Cras fringilla nunc et nulla bibendum rhoncus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam congue suscipit quam nec elementum. Suspendisse consequat eros leo, id volutpat eros.

Quisque sollicitudin luctus magna vel dignissim. Vestibulum ac condimentum quam. Etiam et lacus a libero pellentesque lobortis et lacinia lectus. Suspendisse potenti. Praesent ultrices lacinia leo, nec lacinia eros egestas ac. Suspendisse lobortis lacinia sem nec rutrum. Sed aliquet, lorem quis blandit gravida, ligula tortor hendrerit ligula, ac porta augue velit a arcu. Maecenas sed justo purus, at pretium quam. Donec tortor tellus, lobortis rhoncus feugiat vestibulum, ullamcorper eget mauris. Sed eu tortor leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Morbi risus massa, condimentum sit amet vulputate sed, interdum vitae lacus. Sed dapibus nibh et diam dictum vel eleifend tellus varius. Suspendisse commodo gravida massa, ut congue massa dapibus ac. Ut eleifend hendrerit tristique. Nam euismod erat at nunc fermentum a ullamcorper mauris imperdiet. Vivamus tellus nisi, rhoncus id sollicitudin ut, pharetra a ipsum. Cras adipiscing sem vel tellus auctor eleifend. Nunc viverra adipiscing urna, non tristique diam ullamcorper at. Quisque scelerisque, nisi et suscipit accumsan, risus arcu pretium massa, vel pharetra sem risus a arcu. Integer sit amet rhoncus urna. Morbi at felis vitae mauris porttitor blandit a at turpis.

Mauris vulputate ligula at dui vehicula consectetur. Nullam eget tortor sit amet tortor luctus sodales. Aenean porttitor dui ac velit malesuada pretium. Aenean suscipit imperdiet metus, ut sodales quam luctus non. Nulla vel urna massa. Etiam eget augue a sapien ultrices ultricies. Cras convallis congue ligula, vel fermentum nulla congue eu. In faucibus, odio quis tempor aliquet, sem ante posuere dolor, eget feugiat lacus eros id elit. Nam nisi neque, suscipit et interdum suscipit, auctor vel metus. Etiam vel ullamcorper magna. Suspendisse nec mi et sapien tristique vestibulum. Integer odio ante, commodo sit amet aliquam lobortis, posuere vitae felis. Pellentesque sed ipsum in sapien semper sollicitudin molestie non massa.

Quisque ullamcorper dui turpis. Aliquam non neque diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque, libero nec ullamcorper elementum, est elit bibendum sapien, nec placerat dolor lectus in velit. Sed imperdiet egestas tincidunt. Proin urna velit, porttitor nec semper nec, sollicitudin ut eros. Donec hendrerit lacus vitae nisi molestie vel scelerisque felis sagittis. Nunc consequat arcu tempus tortor commodo eget gravida neque vulputate. Sed gravida ligula sit amet tellus sollicitudin a convallis ligula consequat. Vivamus tellus diam, vulputate et convallis nec, vestibulum quis velit. Pellentesque suscipit massa non ante porta lacinia sed at leo. Aenean ut justo tortor. Nullam at condimentum lorem. Vestibulum dapibus diam in est pretium viverra. Quisque pharetra faucibus mi non lacinia.

Aliquam vel egestas nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis aliquam tempus nunc, id commodo neque sagittis ut. Integer ac nisi vel lorem molestie pharetra ut eget diam. Maecenas nulla mauris, lobortis id suscipit sed, pharetra vel mi. Aenean ut orci ac est dignissim placerat eu vitae enim. Fusce at vehicula augue. Aenean pulvinar mi viverra sapien commodo et fermentum massa interdum. Sed sit amet nibh nec justo pellentesque blandit vel sed nunc.

Nulla bibendum congue lectus, ut auctor nisi condimentum ac. Sed sed dolor lacus, vel feugiat justo. Pellentesque fringilla turpis eget nibh lacinia pulvinar. Suspendisse in ante diam. Pellentesque sapien est, convallis sed auctor in, varius a nisl. Vivamus metus arcu, sagittis eu volutpat at, vehicula nec dolor. Proin rhoncus porta mi, sit amet posuere sapien tincidunt et. Praesent scelerisque eros sit amet nisi egestas scelerisque faucibus orci imperdiet.

Integer dapibus ligula at nunc tristique tincidunt. Quisque odio ligula, tincidunt sed auctor sit amet, porta placerat quam. Nam pellentesque suscipit ante, at interdum justo sollicitudin eu. Sed cursus est at lacus faucibus facilisis porta ante egestas. Vivamus ornare elit eu massa malesuada vulputate eu id ipsum. Nullam aliquet arcu vel nisl luctus eleifend. Pellentesque posuere, est sed accumsan auctor, urna dui imperdiet sem, at accumsan leo nisi at arcu. Proin interdum dignissim posuere. Nullam risus nisi, ultricies sed varius non, rhoncus at metus. Sed nec arcu odio, quis porttitor leo. Nam odio diam, iaculis faucibus dictum non, ultricies congue nunc. Etiam luctus, elit sed pharetra mattis, mi massa elementum nisi, a suscipit leo nisi vitae dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam erat volutpat. Morbi ullamcorper lobortis urna sit amet tempus. Duis in semper lacus.

Mauris mi sapien, tempor non convallis at, molestie quis neque. Morbi metus ligula, accumsan at fringilla et, mattis sit amet orci. Pellentesque eget ipsum metus, sit amet vehicula risus. Phasellus convallis porttitor metus, fringilla faucibus orci luctus semper. Aenean vel nibh ac lorem mattis vehicula. Pellentesque accumsan tincidunt leo, sit amet rhoncus leo convallis in. Nullam suscipit feugiat sem et aliquet. Sed molestie condimentum leo, a tristique ante accumsan eu. Maecenas nunc purus, vulputate ac rutrum eu, rutrum nec nulla. Sed nec urna elit. Suspendisse at dolor nec quam vehicula lacinia. Aenean porta tincidunt sapien. Donec sed nulla lorem, non congue velit. Suspendisse potenti.

Nunc diam nisl, vestibulum eu posuere sed, laoreet vitae metus. Proin sapien metus, ornare gravida semper mollis, consequat id orci. Aenean vel magna at elit posuere fermentum vel hendrerit arcu. Vestibulum erat ligula, sagittis ut faucibus in, convallis in metus. Aliquam rutrum ullamcorper arcu, nec eleifend dolor auctor eget. Nulla velit lacus, adipiscing quis cursus sed, euismod et quam. Quisque ut magna diam, quis elementum eros. Suspendisse placerat faucibus sapien, eget congue sapien ullamcorper non. Donec lacinia mauris in risus molestie a consequat risus malesuada. Aenean sagittis ante eu arcu suscipit imperdiet. Phasellus mollis tristique lacinia. Nullam tincidunt, leo vitae fringilla congue, lectus turpis vehicula nulla, laoreet suscipit lacus lacus sed sem. Donec sodales malesuada neque, et mollis quam fermentum non.

Morbi sit amet eros a odio dignissim varius. Nunc aliquam sagittis turpis vitae luctus. Aliquam accumsan turpis varius metus elementum nec aliquam elit pulvinar. Nulla porta tortor quis mauris pharetra quis pretium ligula mollis. Etiam ornare egestas cursus. Nullam est nisi, vestibulum ut varius in, aliquam quis purus. Mauris cras amet.
"""
		broadcaster['/atmosphere/test'].broadcast('[1-server] ' + message)
		broadcaster['/atmosphere/test'].broadcast('[2-server] ' + message)
		render ''
	}
}
